### ISSUE TITLE
Command for testing and evaluation is giving error

### ISSUE THREAD

**Issue by krishnam-h** [DeepSoftwareAnalytics/CAST#1]
This is the error I get while running the command : $ python casts.py  -cf_file "TL_CodeSum.json"  -ddp False  -only_test True

File "casts.py", line 757, in <module>
    main(cf)
  File "casts.py", line 424, in main
    raise IOError('No such file: %s' % config.model_save_path)
OSError: No such file: ../output\TL_CodeSum\model.pth

**Comment by s1530129650** [comment]
The size of the model is too big to upload. You should train the model,  save it in the `config.model_save_path`, and then evaluate the performance. Thanks.
